README updates
ploigos/ploigos-software-factory-operator pull request #183
Opened 2021-05-18 19:12 UTC by andymiller96

switch namespace to environment variable and make ordered list more ascii-doc...y (remove explicit numbering)

2021-05-18 19:15 UTC, andykrohg requested changes

2021-05-18 19:15 UTC, andykrohg commented on README.adoc
> +This operator powers OpenShift-based deployments of https://ploigos.github.io/ploigos-docs/[Ploigos] - a $PLOIGOS_PROJECT ecosystem modeled after the US DoD's https://dodcio.defense.gov/Portals/0/Doc
Oops 😄

2021-05-18 19:15 UTC, andykrohg commented on README.adoc
> +* *TsscPlatform*: an all-in-one resource for provisioning pre-wired infrastructure like a CI tool, static code analysis server, artifact repository, and other services that support a $PLOIGOS_PROJECT
Not sure this was intended :)

2021-05-19 20:13 UTC, christophermay07 approved these changes

2021-05-19 20:15 UTC, andykrohg approved these changes

2021-05-19 20:15 UTC, merged